### ISSUE TITLE
Failed to activate the ide-css package

### ISSUE THREAD

**Issue by Alijens** [liuderchi/ide-css#11]
[Enter steps to reproduce:]

1. Click enable in settings menu
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-css](https://github.com/liuderchi/ide-css) package 0.2.0

### Stack Trace

Failed to activate the ide-css package

```
At Package not initialized

Error: Package not initialized
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:48:15)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:690:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:439:30)
    at ~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.21.2/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.21.2/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.21.2/resources/app/src/package-manager.js:245:18)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -9:55.6.0 editor:toggle-line-comments (input.hidden-input)
  7x -9:53.1.0 core:backspace (input.hidden-input)
     -9:33.5.0 core:undo (input.hidden-input)
 22x -7:16.8.0 core:backspace (input.hidden-input)
     -7:10 core:confirm (input.hidden-input)
  2x -1:33.6.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  3x -1:23.5.0 outline-view:toggle (div.panels-item)
```

### Non-Core Packages

```
atom-formatter-jsbeautify 1.1.2 
atom-ide-ui 0.5.4 
atom-languageclient 1.0.7 
block-comment-lines 0.2.4 
busy-signal 1.4.3 
color-picker 2.2.5 
console-log 1.10.0 
file-watcher 1.2.6 
flow 0.5.3 
ftp-remote-edit 0.12.6 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-html 0.4.1 
ide-typescript 0.6.2 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-dust-ng 0.1.1 
less-than-slash 0.17.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-scss-lint 3.1.1 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
sublime-block-comment 0.5.1 
sync-settings 0.8.3 
```

**Comment by liuderchi** [comment]
@Alijens sorry for the late reply

Please disable `linter-csslint`, `linter-scss-lint` then install latest `ide-css` and `atom-ide-ui`.
