### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by brunoczim** [liuderchi/ide-css#18]
[Enter steps to reproduce:]

1. Have this package installed
2. Open atom (I opened on a Rust source file which also uses the atom-ide package)

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Debian GNU/Linux
**Thrown From**: [ide-css](https://github.com/liuderchi/ide-css) package 0.2.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /home/bruno/.atom/packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
  2x -0:40.2.0 core:move-down (input.hidden-input)
  2x -0:39.8.0 core:move-up (input.hidden-input)
     -0:39.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.2 
atom-ternjs 0.18.3 
autocomplete-racer 0.1.3 
build-gradle 0.6.0 
busy-signal 1.4.3 
color-picker 2.2.5 
GAS-x86_64-highlighter 0.3.7 
ide-css 0.2.0 
ide-java 0.8.1 
ide-php 0.7.8 
ide-rust 0.14.0 
ide-scala 0.5.0 
ide-typescript 0.7.5 
intentions 1.1.5 
language-assembly 0.7.2 
language-ats 0.1.6 
language-ebnf 0.1.0 
language-elixir 0.22.0 
language-erlang 3.2.0 
language-gradle 0.0.5 
language-groovy 0.7.0 
language-haskell 1.17.3 
language-htaccess 0.2.0 
language-idris 0.4.10 
language-jasmin 0.2.0 
language-latex 1.1.1 
language-luajit 1.2.0 
language-qcl 0.5.0 
language-rust 0.4.12 
language-scala 1.1.9 
language-smalltalk 1.0.2 
language-twig 1.6.3 
language-x86 1.0.1 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-rust 0.8.4 
linter-ui-default 1.7.1 
php-getters-setters 0.5.5 
php-integrator-autocomplete-plus-legacy-php56 1.0.1 
php-integrator-base-legacy-php56 1.0.1 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation-legacy-php56 1.0.1 
php-integrator-refactoring-legacy-php56 1.0.1 
php-integrator-tooltips-legacy-php56 1.1.6 
project-manager 3.3.5 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by liuderchi** [comment]
@brunoczim When having cursor focused on the Rust file, 
what's the result if you dispatch Atom command `Editor: Log Cursor Scope`? 

(I want to confirm that ide-css is really digesting your Rust file, which is actually not often seen)

**Comment by Arcanemagus** [comment]
Likely related to or a duplicate of https://github.com/mehcode/atom-ide-rust/issues/66.

**Comment by mariogmz** [comment]
This is happening to me to with a Ruby file opened.

**Comment by brunoczim** [comment]
Hey, sorry taking so long, but I am not even using atom anymore
