### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by frost-byte** [liuderchi/ide-css#27]
Not sure how to reproduce this, I just have a project open in atom.  Even if atom isn't the focused application, the message will still pop up.

**Atom**: 1.28.0 ia32
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-css](https://github.com/liuderchi/ide-css) package 0.3.0

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\xxxx\.atom\packages\ide-css\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:194:43)
    at /packages/ide-css/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.4 
atom-debug-ui 1.0.4 
atom-handlebars 1.3.0 
atom-ide-ui 0.12.0 
atom-jinja2 0.6.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-save-all 0.4.1 
atom-ternjs 0.18.3 
atom-typescript undefined 
autocomplete 0.47.0 
autocomplete-modules 2.0.0 
autocomplete-php 0.3.7 
docblockr 0.9.1 
file-icons 2.1.21 
fonts 3.0.3 
git-plus undefined 
highlight-bad-chars 1.0.7 
hyperclick 0.0.0 
ide-css 0.3.0 
ide-html 0.4.2 
ide-php 0.7.14 
ide-typescript 0.7.6 
intentions 1.1.5 
isotope-ui 2.8.5 
jquery-snippets 11.0.0 
language-ansible 0.2.2 
linter 2.2.0 
linter-csslint 2.0.1 
linter-htmlhint 1.4.0 
linter-js-yaml 1.3.0 
linter-php 1.5.1 
linter-tslint 1.9.1 
markdown-preview-plus undefined 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
monokai 0.24.0 
monokai-dark 1.5.0 
package-cop 0.2.10 
php-cs-fixer 4.1.1 
php-debug 0.3.4 
php-hyperclick 1.2.1 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-base undefined 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-twig 4.0.0 
project-manager 3.3.5 
sass-autocompile 0.13.5 
symbol-gen 1.3.1 
symbols-tree-view undefined 
todo-show 2.3.0 
xml-formatter 0.11.0 
```

**Comment by frost-byte** [comment]
Not sure how you are using the vscode-jsonrpc module, but that seems to be something specific to vscode and not atom?

If I add a breakpoint on line 68 of vscode-jsonrpc/lib/messageReader.js - then add a watch in the developer tools for: this.buffer.toString('ascii', 0, current), then the string contains "<--- Last few GCS --->"

I was able to convert the entire buffer to a string and it seemed to refer to @angular/common/locale/os.d.ts.  I don't think this is related to angular, but perhaps how one of my local node packages is linked (it seems like a circular issue, because the path listed for the file seems to show a circular recursion of the directory)

**Comment by frost-byte** [comment]
What's even more frustrating - I have uninstalled and removed your package, and yet it's still being loaded by atom, even though it no longer exists in the .atom/packages
